adding depedencies checking for install and remove package to safely remove and install with prompt

diff --git a/slaptbuild b/slaptbuild
--- a/slaptbuild
+++ b/slaptbuild
@@ -77,7 +77,7 @@ update_sbo()
 
 search_sbo()
 {
-  echo "## finding package contains ${@:2}..."
+  echo "## finding package contains ${@:2}"
   
   for param in ${@:2}
   do
@@ -94,27 +94,45 @@ search_sbo()
 
 info_sbo()
 {
-  echo "## get package info of $1..."
-  while IFS=' ' read -ra line
-  do
-    prgpath=${line[0]}
-    prgnam=${line[1]}
-    if [[ "$prgnam" = "$1" ]]
-    then
-      cat $prgpath/"slack-desc"
-    fi
-  done < $SLAPTBUILD_DB
+  echo "## get package info of $1"
+  pkg=`cat $SLAPTBUILD_DB|grep " $1 "`
+  if [[ ! -z $pkg ]]
+  then
+    pkg_detail=($pkg)
+    prgpath=${pkg_detail[0]}
+    cat $prgpath/"slack-desc"
+  else
+    echo "pkg not found: $1"
+  fi
   echo "## finished."
 }
 
 remove_sbo()
 {
-  echo "## removing installed package contains ${@:2}..."
+  # check depedencies and save it to pkgs_toremove variable
+  echo "## checking depedencies for: ${@:2}"
+  check_rempkgdeps_sbo ${@:2}
+
+  echo "## removing installed pkg(s) contains: $pkgs_toremove"
+  if [[ ! -z $pkgs_toremove_invalid ]]
+  then
+    echo "## invalid pkg(s): $pkgs_toremove_invalid"
+  fi
+
+  read -p "remove pkg(s) (y/n): " confirm
+  if [[ ! -z $confirm  ]] && [[ $confirm = "n" || $confirm = "N" ]]
+  then
+    exit
+  fi
+
+  # split to array
+  pkgs=($pkgs_toremove)
+
   if [[ $# -ge 2 ]]
   then
     # remove old installed buffer
     rm -f $SLAPTBUILD_INSTALLED_DB.tmp
-    for pkg in ${@:2}
+    for pkg in ${pkgs[@]}
     do
       while IFS=' ' read -ra line
       do
@@ -144,7 +162,7 @@ remove_sbo()
 
 install_pkg()
 {
-  echo "## installing ${@:2}..."
+  echo "## installing ${@:2}"
   for pkg in ${@:2}
   do
     if [[ -f $pkg ]]
@@ -166,114 +184,223 @@ install_pkg()
 
 install_sbo()
 {
-  echo "## installing ${@:2}..."
-  for prg in ${@:2}
+  # check depedencies and save it to pkgs_toinstall variable
+  echo "## checking depedencies for: ${@:2}"
+  check_pkgdeps_sbo ${@:2}
+
+  echo "## install pkg(s) contains: $pkgs_toinstall..."
+  if [[ ! -z $pkgs_toinstall_invalid ]]
+  then
+    echo "## invalid pkg(s): $pkgs_toinstall_invalid"
+  fi
+  
+  read -p "install pkg(s) (y/n): " confirm
+  if [[ ! -z $confirm  ]] && [[ $confirm = "n" || $confirm = "N" ]]
+  then
+    exit
+  fi
+
+  # split to array
+  pkgs=($pkgs_toinstall)
+
+  # install all packages with depedencies in pkgs array
+  for prg in ${pkgs[@]}
   do
-    while IFS=' ' read -ra line
-    do
-      prgpath=${line[0]}
-      prgnam=${line[1]}
-      version=${line[2]}
+    pkg=`cat $SLAPTBUILD_DB|grep " $prg "`
+    if [[ ! -z $pkg ]]
+    then
+      pkg_detail=($pkg)
+      prgpath=${pkg_detail[0]}
+      prgnam=${pkg_detail[1]}
+      version=${pkg_detail[2]}
       PKGVER=""
       
-      if [[ "$prgnam" = "$prg" ]]
+      cd $prgpath
+      argv0="$0"
+      BASH_ARGV0=$prgpath/$prgnam.SlackBuild
+
+      # get package info
+      source $prgpath/$prgnam.info
+
+      # if package has same name and version skip it
+      installed=$(cat $SLAPTBUILD_INSTALLED_DB|awk '{print $1" "$2}'|grep -w "$prgnam $prgnam-$version"|xargs)
+      if [[ -n $installed ]] && [[ "$1" = "install" ]]
       then
-	cd $prgpath
-        argv0="$0"
-        BASH_ARGV0=$prgpath/$prgnam.SlackBuild
-
-        # get package info
-        source $prgpath/$prgnam.info
-
-        # if package has same name and version skip it
-        installed=$(cat $SLAPTBUILD_INSTALLED_DB|awk '{print $1" "$2}'|grep -w "$prgnam $prgnam-$version"|xargs)
-        if [[ -n $installed ]] && [[ "$1" = "install" ]]
-        then
-          echo ">> $prgnam $version already installed."
-          break
-        fi
-    
-        blacklisted=`cat $SLAPTBUILD_BLACKLIST_DB|grep -e "^${prgnam}$"|xargs`
-        if [[ -n $blacklisted ]]
-        then
-          echo ">> skip, $prgnam blacklisted."
-          break
-        fi
-
-        # download source for build process
-        downloads=""
-        if [[ ! "${DOWNLOAD,,}" = "unsupported" ]]
-        then
-          downloads=$DOWNLOAD
-        elif [[ ! "${DOWNLOAD_x86_64,,}" = "unsupported" ]]
-        then
-          downloads=$DOWNLOAD_x86_64
-        elif [[ ! "${DOWNLOAD_i586,,}" = "unsupported" ]]
-        then
-          downloads=$DOWNLOAD_i586
-        elif [[ ! "${DOWNLOAD_i586,,}" = "unsupported" ]]
-        then
-          downloads=$DOWNLOAD_i686
-        fi
-        
-        wget -P $prgpath -c -t inv $downloads
-
-        source $prgpath/$prgnam.SlackBuild
-
-        # check if package already generated
-        pkgout=$PRGNAM-${PKGVER:-$VERSION}-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
-        #if [[ -n $PKGVER ]]
-        #then
-        #  pkgout=$PRGNAM-$PKGVER-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
-        #fi
-
-        # pkg path
-        if [[ -f $OUTPUT/$pkgout ]]
-        then
-          # if there are no errors
-          if [[ $? -eq 0 ]] && [[ -n $pkgout ]]
-          then
-            # check if package already installed
-            # if so do reinstall or upgrade or downgrade
-            installed=$(cat $SLAPTBUILD_INSTALLED_DB|awk '{print $1}'|grep -w "$prgnam"|xargs)
-            if [[ -n $installed ]]
-            then
-              remove_sbo "" $prgnam
-            fi
-
-            # install package if success
-            /sbin/installpkg $OUTPUT/$pkgout
-
-            ## update installed app list
-            installed=$(cat $SLAPTBUILD_INSTALLED_DB|awk '{print $1 $2}'|grep -w "$prgnam $version"|grep -e "\S"|xargs)
-            if [[ -z $installed ]]
-            then
-              echo $PRGNAM $pkgout >> $SLAPTBUILD_INSTALLED_DB
-            fi
-
-            ## remove downloaded source if success
-            arr_downloads=( $downloads )
-            for download in "${arr_downloads[@]}"
-            do
-              downloadedfile=$prgpath/${download##*/}
-              if [[ -f $downloadedfile ]]
-              then
-                rm -f $downloadedfile
-              fi
-            done
-          fi
-        fi
-        BASH_ARGV0=$argv0
-        cd -
+        echo ">> $prgnam $version already installed."
+        continue
       fi
-    done < $SLAPTBUILD_DB
+  
+      blacklisted=`cat $SLAPTBUILD_BLACKLIST_DB|grep -e "^${prgnam}$"|xargs`
+      if [[ -n $blacklisted ]]
+      then
+        echo ">> skip, $prgnam blacklisted."
+        continue
+      fi
+
+      # download source for build process
+      downloads=""
+      if [[ ! "${DOWNLOAD,,}" = "unsupported" ]]
+      then
+        downloads=$DOWNLOAD
+      elif [[ ! "${DOWNLOAD_x86_64,,}" = "unsupported" ]]
+      then
+        downloads=$DOWNLOAD_x86_64
+      elif [[ ! "${DOWNLOAD_i586,,}" = "unsupported" ]]
+      then
+        downloads=$DOWNLOAD_i586
+      elif [[ ! "${DOWNLOAD_i586,,}" = "unsupported" ]]
+      then
+        downloads=$DOWNLOAD_i686
+      fi
+      
+      wget -P $prgpath -c -t inv $downloads
+
+      source $prgpath/$prgnam.SlackBuild
+
+      # check if package already generated
+      pkgout=$PRGNAM-${PKGVER:-$VERSION}-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
+      #if [[ -n $PKGVER ]]
+      #then
+      #  pkgout=$PRGNAM-$PKGVER-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
+      #fi
+
+      # pkg path
+      if [[ -f $OUTPUT/$pkgout ]]
+      then
+        # if there are no errors
+        if [[ $? -eq 0 ]] && [[ -n $pkgout ]]
+        then
+          # check if package already installed
+          # if so do reinstall or upgrade or downgrade
+          installed=$(cat $SLAPTBUILD_INSTALLED_DB|awk '{print $1}'|grep -w "$prgnam"|xargs)
+          if [[ -n $installed ]]
+          then
+            remove_sbo "" $prgnam
+          fi
+
+          # install package if success
+          /sbin/installpkg $OUTPUT/$pkgout
+
+          ## update installed app list
+          installed=$(cat $SLAPTBUILD_INSTALLED_DB|awk '{print $1 $2}'|grep -w "$prgnam $version"|grep -e "\S"|xargs)
+          if [[ -z $installed ]]
+          then
+            echo $PRGNAM $pkgout >> $SLAPTBUILD_INSTALLED_DB
+          fi
+
+          ## remove downloaded source if success
+          arr_downloads=( $downloads )
+          for download in "${arr_downloads[@]}"
+          do
+            downloadedfile=$prgpath/${download##*/}
+            if [[ -f $downloadedfile ]]
+            then
+              rm -f $downloadedfile
+            fi
+          done
+        fi
+      fi
+      BASH_ARGV0=$argv0
+      cd - &> /dev/null
+    fi
   done
   echo "## finished."
 }
 
+# program to install after check depedencies
+pkgs_toinstall=""
+pkgs_toinstall_invalid=""
+
+check_pkgdeps_sbo()
+{
+  for prg in ${@}
+  do
+    pkg=`cat $SLAPTBUILD_DB|grep " $prg "`
+    if [[ ! -z $pkg ]]
+    then
+      pkg_detail=($pkg)
+      prgpath=${pkg_detail[0]}
+      prgnam=${pkg_detail[1]}
+      version=${pkg_detail[2]}
+      
+      cd $prgpath
+      argv0="$0"
+      BASH_ARGV0=$prgpath/$prgnam.SlackBuild
+
+      # get package info
+      source $prgpath/$prgnam.info
+      
+      pkgs_toinstall=`echo "$prg $pkgs_toinstall" | awk '{for (i=1;i<=NF;i++) if (!a[$i]++) printf("%s%s",$i,FS)}{printf("\n")}'`
+
+      # check depedencies from REQUIRES variable from .info file
+      if [[ ${REQUIRES+x} ]] && [[ ! -z "$REQUIRES" ]]
+      then
+        IFS=' '
+        read -s requiresDeps <<< "$REQUIRES"
+        for dep in "${requiresDeps[@]}"
+        do
+          check_pkgdeps_sbo $dep
+        done
+        unset IFS
+      fi
+
+      BASH_ARGV0=$argv0
+      cd - &> /dev/null
+    else
+      pkgs_toinstall_invalid=`echo "$prg $pkgs_toinstall_invalid" | awk '{for (i=1;i<=NF;i++) if (!a[$i]++) printf("%s%s",$i,FS)}{printf("\n")}'`
+    fi
+  done
+}
+
+# program to install after check depedencies
+pkgs_toremove=""
+pkgs_toremove_invalid=""
+
+check_rempkgdeps_sbo()
+{
+  for prg in ${@}
+  do
+    pkg=`cat $SLAPTBUILD_DB|grep " $prg "`
+    if [[ ! -z $pkg ]]
+    then
+      pkg_detail=($pkg)
+      prgpath=${pkg_detail[0]}
+      prgnam=${pkg_detail[1]}
+      version=${pkg_detail[2]}
+      
+      cd $prgpath
+      argv0="$0"
+      BASH_ARGV0=$prgpath/$prgnam.SlackBuild
+
+      # get package info
+      source $prgpath/$prgnam.info
+      
+      pkgs_toremove=`echo "$prg $pkgs_toremove" | awk '{for (i=1;i<=NF;i++) if (!a[$i]++) printf("%s%s",$i,FS)}{printf("\n")}'`
+      
+      # check depedencies from REQUIRES variable from .info file
+      if [[ ${REQUIRES+x} ]] && [[ ! -z "$REQUIRES" ]]
+      then
+        IFS=' '
+        read -s requiresDeps <<< "$REQUIRES"
+        for dep in ${requiresDeps[@]}
+        do
+          # let check the pkg deps
+          check_rempkgdeps_sbo $dep
+        done
+        unset IFS
+      fi
+
+      BASH_ARGV0=$argv0
+      cd - &> /dev/null
+    else
+      pkgs_toremove_invalid=`echo "$prg $pkgs_toremove_invalid" | awk '{for (i=1;i<=NF;i++) if (!a[$i]++) printf("%s%s",$i,FS)}{printf("\n")}'`
+    fi
+  done
+}
+
 upgrade_sbo()
 {
-  echo "## upgrade installed package..."
+  echo "## upgrade installed pkg(s)"
   while IFS= read -ra line
   do
     install_sbo "install" ${line[0]}
@@ -283,7 +410,7 @@ upgrade_sbo()
 
 reinstall_all_sbo()
 {
-  echo "## reinstall installed package..."
+  echo "## reinstall installed pkg(s)"
   while IFS= read -ra line
   do
     install_sbo "reinstall" ${line[0]}
@@ -293,7 +420,7 @@ reinstall_all_sbo()
 
 locked_pkg()
 {
-  echo "## change package ${@:2} lock state..."
+  echo "## change pkg(s) ${@:2} lock state"
   for pkg in ${@:2}
   do
     pkgnam=`basename $pkg|sed 's/\-[0-9]\+\.[0-9]\+.*$//g'|xargs`
@@ -336,7 +463,7 @@ locked_pkg()
 
 blacklisted_pkg()
 {
-  echo "## finding blacklisted package contains ${@:2}..."
+  echo "## finding blacklisted pkg(s) contains: ${@:2}"
   if [[ $# -lt 2 ]]
   then
     while IFS= read -r line
@@ -360,7 +487,7 @@ blacklisted_pkg()
 
 installed_sbo()
 {
-  echo "## finding installed package contains ${@:2}..."
+  echo "## finding installed pkg(s) contains ${@:2}"
   if [[ $# -lt 2 ]]
   then
     while IFS= read -r line
